#!/bin/bash

mkdir -p /tmp/rom && cd /tmp/rom

# URL file
url=https://transfer.sh/ePA/RevengeOS-3.2-Q-UNOFFICIAL-certus-20210528-1441.zip

# aria2c
time aria2c $url -x16 -s50

# rclone
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
time rclone copy * Hisyam99:roms -P
rm -rf ~/.config/rclone
